version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

build:
  os: ubuntu-24.04
  commands:
    - pip install -r docs/requirements.txt
    - sphinx-build -b html docs/source docs/build/html

python:
  install:
    - requirements: docs/requirements.txt
