version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

build:
  os: ubuntu-24.04
  tools:
  python: "3.12.7"

python:
  install:
    - requirements: docs/requirements.txt
